import Head from "next/head";

import Header from "@/Components/Header";
import Topcards from "@/Components/Topcards";
import Barchart from "@/Components/Barchart";
import Recentorders from "@/Components/Recentorders";
import DoghnutChart from "@/Components/DoghnutChart";
import Sharethoughtsform from "@/Components/Sharethoughtsform";
import Storage from "@/Components/Storage";
import EmailSubscribers from "@/Components/EmailSubscribers";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 min-h-screen">
        <Header />
        <Topcards />
        <div className=" p-4 gap-4 lg:gap-5 grid grid-cols-1 md:grid-cols-3 ">
          <Barchart />
          <Recentorders />
        </div>
        <div className="p-4 gap-4 lg:gap-8 grid grid-cols-1 md:grid-cols-2 my-4 h-auto ">

<Storage />
<EmailSubscribers />
        </div>
        <div className=" p-4 gap-4 lg:gap-7 grid grid-cols-1 md:grid-cols-3 h-auto ">
          <DoghnutChart />
          <Sharethoughtsform />
        </div>
      </main>
    </>
  );
}
