import Head from 'next/head'
import Image from 'next/image'
import Header from '@/Components/Header'
import Topcards from '@/Components/Topcards'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-50 min-h-screen'>
        <Header />
        <Topcards />
      </main>
    </>
  )
}
